[project]
name = "r-template"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
copier = ">=9.2.0,<9.3"

[pypi-dependencies]
jinja2-shell-extension = "*"
